### PR TITLE
make desc package work on Windows

### LINKED ISSUE #335: LoadFileDescriptor with dependency proto fails on Windows
# Env
OS: Win 10 1909
protoreflect Version: 1.7.0

# Description
I have a proto file,  contains some other proto dependencies like: gogole standard proto. 
Use `desc.LoadFileDescriptor(xx/yy/custom.proto)`  will failed.

in `imports.go`, it will translate proto file path:

```
func ResolveImport(importPath string) string {
	importPath = clean(importPath)
	globalImportPathMu.RLock()
	defer globalImportPathMu.RUnlock()
	reg := globalImportPathConf[importPath]
	if reg == "" {
		return importPath
	}
	return reg
}

func clean(path string) string {
	if path == "" {
		return ""
	}
	path = filepath.Clean(path)
	if path == "." {
		return ""
	}
	return strings.TrimPrefix(path, dotPrefix)
}
```

for example, from "google/protobuf/any.proto" to "google\protobuf\any.proto", cause not found in `filesCache`.

### PR DESCRIPTION
**Pull request by jhump**
This is an attempt to make this repo work correctly on Windows -- at least verifying that tests pass 🤞 

Hopefully, we can get this branch green and resolve #335

### CODE REVIEW

**Comment by bufdev** [comment]
Oh this is going to be a fun one. If it passes on the first run, I'll be impressed :-)

**Comment by rogchap** [comment]
Any progress? Would be great to have Windows support.

**Comment by jhump** [comment]
Finally getting around to trying this out on an actual Windows PC and.... it passes, all green.

When installing git for Windows, it did ask me about line ending conventions. I configured it to checkout "as is" and push "as is" (e.g. don't attempt to do any LF-> CRLF -> LF conversions/mangling to accommodate dumb Windows tools that expect CRLF). And it passed all tests first try.

So I am pretty sure that the build failure, which indicates a line ending issue, is because the Travis CI machine that was running the build was configured to convert line endings on checkout. So the test files had different line endings and therefore some of the line endings and source position information in source code info was different than expected (the expectations are all based on the files "as is" with simple LF line endings).

I still need to re-base this PR and update it to have Circle CI run the tests on Windows. But one thing that is missing is a test file that _deliberately_ has Windows-style line endings, to make sure that things like source info and comments emitted by `protoparse` match the behavior of running `protoc` on Windows.

**Comment by jhump** [comment]
> But one thing that is missing is a test file that _deliberately_ has Windows-style line endings, to make sure that things like source info and comments emitted by `protoparse` match the behavior of running `protoc` on Windows.

I'll have to deal with this part later. For now, the fix in the first commit (combined with turning off crlf conversion in git in CI) gets the build green. So this seems like a valuable partial, so that Windows users are mostly able to make use of this repo.

**Comment by jhump** [comment]
@rogchap, apologies for the long delay. Do take a look at latest master and file a new issue if you see something else that is still messed up on Windows.

**Pull request merged**
