### PR TITLE
fix panic

### PR DESCRIPTION
**Pull request by fukeainideren**
image

image

### CODE REVIEW

**Comment by jhump** [comment]
These seem like perfectly reasonable panics: you shouldn't be calling these methods with a nil receiver.

I suspect the panics you are seeing are happening inside the proto runtime code and are not actually problems: the proto runtime recovers from these panics and behaves correctly thereafter. Take a look at #341 for more details.

**Comment by fukeainideren** [comment]
> These seem like perfectly reasonable panics: you shouldn't be calling these methods with a nil receiver.
> 
> I suspect the panics you are seeing are happening inside the proto runtime code and are not actually problems: the proto runtime recovers from these panics and behaves correctly thereafter. Take a look at #341 for more details.

let me offer a testing file

**Comment by jhump** [comment]
@fukeainideren, if you get a chance to revisit this, and have a test file and/or more observations about this behavior and why you think a change is needed, please open a new issue, so we can discuss before re-opening this pull request.

**Comment by zzxalan** [comment]
image
i find the bug is from idea when debug. but how to avoid?

**Comment by jhump** [comment]
@zzxalan, the code in the screenshot appears to have _nothing_ to do with this protoreflect library.

Also, `soonNil` in your example is a nil pointer (it defaults to that value when declared on line 16 and then you explicitly set to that value on line 17). You cannot dereference fields through a nil pointer. (You _can_ on the other hand invoke methods for a nil receiver, but that may cause the same panic later in the method body; refer to the type's documentation for whether methods are safe to call with nil pointers.)

**Pull request closed without merging**
