### PR TITLE
better support for well-known-types when marshaling dynamic messages to/from JSON

### LINKED ISSUE #99: WKT do not appear to work with MessageDescriptors retrieved from FindMessage after CreateFileDescriptorFromSet
I have a fully-valid FileDescriptorSet created from protoc with `--include_imports`, that contains `google/protobuf/duration.proto` in the `files` list, and the message I try to operate on contains a `google.protobuf.Duration` field named `duration`. When I create a `DynamicMessage` with `dynamic.NewMessage` (or using the default message factory with the WKT resolver and `NewDynamicMessage`) from a `MessageDescriptor` from `FindMessage` from something returned from `CreateFileDescriptorFromSet` where the message is contained in the last file. When I try to unmarshal `'{"duration":"10.000s"}'`, I get the error `Bad input. Expecting start of JSON object: '{'. Instead got: 10.000s.`. I believe this is related to the fact that `dynamic/message_factory.go` relies on reflection to see if there is a registered WKT message in the `github.com/golang/protobuf` globals, when this library shouldn't rely on the global maps within `github.com/golang/protobuf` at all (ie calls to `proto.MessageType`) - it makes this unusable for `github.com/gogo/protobuf` users, and belies the purpose of being able to do everything dynamically with `FileDescriptorSets` in the first place :-)

I know this is a really weak explanation, I'll try to create a test that reproduces this, but wanted to kick off the conversation.

Great library btw!

### PR DESCRIPTION
**Pull request by jhump**
This should resolve #99.

@peter-edge, this will cause a small merge conflict in #100.

### CODE REVIEW

**Comment by peter-edge** [comment]
Looks fine to me, but I think you should get all the Well-Known Types, not just the ones they includes in `ptypes`:

```
[~/Library/Caches/prototool/Darwin/x86_64/protobuf/3.5.1/include]
$ tree
.
└── google
    └── protobuf
        ├── any.proto
        ├── api.proto
        ├── compiler
        │   └── plugin.proto
        ├── descriptor.proto
        ├── duration.proto
        ├── empty.proto
        ├── field_mask.proto
        ├── source_context.proto
        ├── struct.proto
        ├── timestamp.proto
        ├── type.proto
        └── wrappers.proto
```

I have the following mappings in https://github.com/uber/prototool/blob/dev/internal/wkt/wkt.go:

```
	"google/protobuf/any.proto":             "github.com/golang/protobuf/ptypes/any",
		"google/protobuf/api.proto":             "google.golang.org/genproto/protobuf/api",
		"google/protobuf/compiler/plugin.proto": "github.com/gogo/protobuf/protoc-gen-go/plugin",
		"google/protobuf/descriptor.proto":      "github.com/gogo/protobuf/protoc-gen-go/descriptor",
		"google/protobuf/duration.proto":        "github.com/golang/protobuf/ptypes/duration",
		"google/protobuf/empty.proto":           "github.com/golang/protobuf/ptypes/empty",
		"google/protobuf/field_mask.proto":      "google.golang.org/genproto/protobuf/field_mask",
		"google/protobuf/source_context.proto":  "google.golang.org/genproto/protobuf/source_context",
		"google/protobuf/struct.proto":          "github.com/golang/protobuf/ptypes/struct",
		"google/protobuf/timestamp.proto":       "github.com/golang/protobuf/ptypes/timestamp",
		"google/protobuf/type.proto":            "google.golang.org/genproto/protobuf/ptype",
		"google/protobuf/wrappers.proto":        "github.com/golang/protobuf/ptypes/wrappers",
```

**Comment by peter-edge** [comment]
Whoops, and there I discovered a bug in my code, here's the right golang/protobuf mappings (I had two gogo/protobuf mappings in there):

```
		"google/protobuf/any.proto":             "github.com/golang/protobuf/ptypes/any",
		"google/protobuf/api.proto":             "google.golang.org/genproto/protobuf/api",
		"google/protobuf/compiler/plugin.proto": "github.com/golang/protobuf/protoc-gen-go/plugin",
		"google/protobuf/descriptor.proto":      "github.com/golang/protobuf/protoc-gen-go/descriptor",
		"google/protobuf/duration.proto":        "github.com/golang/protobuf/ptypes/duration",
		"google/protobuf/empty.proto":           "github.com/golang/protobuf/ptypes/empty",
		"google/protobuf/field_mask.proto":      "google.golang.org/genproto/protobuf/field_mask",
		"google/protobuf/source_context.proto":  "google.golang.org/genproto/protobuf/source_context",
		"google/protobuf/struct.proto":          "github.com/golang/protobuf/ptypes/struct",
		"google/protobuf/timestamp.proto":       "github.com/golang/protobuf/ptypes/timestamp",
		"google/protobuf/type.proto":            "google.golang.org/genproto/protobuf/ptype",
		"google/protobuf/wrappers.proto":        "github.com/golang/protobuf/ptypes/wrappers",
```

**Comment by jhump** [comment]
@peter-edge: I got the only ones that have a special JSON formats implemented by `protobuf/jsonpb`: https://github.com/golang/protobuf/blob/master/protoc-gen-go/generator/generator.go#L1708

These are *almost* all of the ones described by the docs for proto3 JSON format:
https://developers.google.com/protocol-buffers/docs/proto3#json
There is only one omission: `fieldmask.proto`. And since `protobuf/jsonpb` doesn't handle it either, I'm okay with leaving it out for now.

**Comment by peter-edge** [comment]
Yep was just about to comment, it's late over here, my apologies :-)

So... LGTM haha 👍

**Comment by peter-edge** [comment]
We should consider replicating https://github.com/golang/protobuf/blob/master/jsonpb/jsonpb_test.go.

**Comment by jhump** [comment]
> We should consider replicating  ...

Perhaps. The tests that are here already run JSON marshaling/unmarshaling against a variety of messages and types and then verifies that the output exactly matches `jsonpb`. If you just mean for catching some of the edge cases, that may be worthwhile. I know there have been recent-ish changes regarding JSON `null` and empty slices(repeated fields) and maps. And I have not yet verified that dynamic message behaves the same way.

**Pull request merged**
