### PR TITLE
desc.Descriptor wraps protoreflect.Descriptor

### LINKED ISSUE #301: Compatibility between protoprint and "google.golang.org/protobuf/reflect/protoreflect"
Is it possible to use the protoprint library with the Google-authored protoreflect library?

(I'm curious about @jhump's general thoughts on the Google protoreflect library. protoprint is not provided by the Google library's functionality and is quite cool, so I'm most interested in using this part of the library.)

### PR DESCRIPTION
**Pull request by jhump**
This is a major overhaul that enables full interop with the protoreflect package in the newer Go protobuf API. It makes it easy to convert between `desc.Descriptor` types and `protoreflect.Descriptor` types.

It was also necessary to make significant changes to `protoparse`, because it would build `desc.Descriptor` instances during linking, that were intermediate artifacts. But that can't work now that `desc.Descriptor` is a wrapper around `protoreflect.Descriptor` because the functions to create the `protoreflect.Descriptor` instances do more validation that cannot succeed at this phase of linking (because options have not yet been interpreted). I had already solved this by creating unexported implementations of the various `protoreflect.Descriptor` interfaces, that wrap descriptor protos and linker state. This means that interpreting options uses `dynamicpb` instead of the `dynamic` package in this repo. All of that is actually implemented in `protoparse`'s _successor_: http://github.com/bufbuild/protocompile. So `protoparse` in this repo, as of this PR, now _wraps_ `protocompile`. 🤯

While fixing some strange issues in the `protoprint` package that occurred after the `protoparse` overhaul, I ended up re-writing how it handles rendering custom options and message literals. It no longer uses the `proto` package's text marshaling functionality but instead has its own custom test marshaling (which also allows it to address how to render qualified names in extensions in message literals and also provides much greater control over formatting and where to put
line breaks, allowing the output to be both readable and more compact).

Resolves #301, #444, and #531.

### CODE REVIEW

**Comment by 89z** [comment]
https://github.com/jhump/protoreflect/issues/418

**Comment by timruffles** [comment]
I've found this library really useful so far, but would love to be able to use it with the newer APIs (e.g. `google.golang.org/protobuf/types/dynamicpb`). Looks like this got paused a while back. Any plans to pick it up again, or would this be usable as it stands with the provisos you've noted?

**Comment by jhump** [comment]
> Looks like this got paused a while back. Any plans to pick it up again, or would this be usable as it stands with the provisos you've noted?

@timruffles, sorry for the very late reply. I was taking a sabbatical for several months, including in April when you wrote this.

My plan is to focus more on https://github.com/jhump/protocompile, a new API for parsing/compiling protos that directly uses the new API v2 libraries. Once that is done and I've got it integrated into https://github.com/bufbuild/buf (replacing the use of `desc/protoparse` in this repo), I will come back and revisit this arc of work.

**Comment by jhump** [comment]
I still need to run `apidiff` on this to make sure that I haven't accidentally broken the exported API.

I don't want this to be a v2 of these packages: for a v2, I plan to intentionally break backwards-compatibility and even remove stuff in here that now overlaps with the v2 API of the protobuf runtime (`desc`, `codec`, and `dynamic`).

**Comment by jhump** [comment]
I've finally confirmed with `apidiff` that this should be a compatible change -- no incompatible changes made to exported APIs. The only changes are below (all additions, which are compatible changes):
```
github.com/jhump/protoreflect/desc:
Compatible changes:
- (*EnumDescriptor).Unwrap: added
- (*EnumDescriptor).UnwrapEnum: added
- (*EnumValueDescriptor).Unwrap: added
- (*EnumValueDescriptor).UnwrapEnumValue: added
- (*FieldDescriptor).Unwrap: added
- (*FieldDescriptor).UnwrapField: added
- (*FileDescriptor).Unwrap: added
- (*FileDescriptor).UnwrapFile: added
- (*MessageDescriptor).Unwrap: added
- (*MessageDescriptor).UnwrapMessage: added
- (*MethodDescriptor).Unwrap: added
- (*MethodDescriptor).UnwrapMethod: added
- (*OneOfDescriptor).Unwrap: added
- (*OneOfDescriptor).UnwrapOneOf: added
- (*ServiceDescriptor).Unwrap: added
- (*ServiceDescriptor).UnwrapService: added
- DescriptorWrapper: added
- WrapDescriptor: added
- WrapEnum: added
- WrapEnumValue: added
- WrapField: added
- WrapFile: added
- WrapFiles: added
- WrapMessage: added
- WrapMethod: added
- WrapOneOf: added
- WrapService: added

github.com/jhump/protoreflect/desc/sourceinfo:
Compatible changes:
- GlobalTypes: added
- TypeResolver: added
- WrapEnum: added
- WrapExtensionType: added
- WrapFile: added
- WrapMessage: added
- WrapMessageType: added
- WrapService: added
```
Despite the significant overhauling of `desc/protoparse`, I've successfully avoided any API incompatibility.

So I will be merging this and awaiting input from folks to see if there is any fall-out. I suspect there will be some performance impact and that the `desc/builder` package will now be much more strict, just due to now wrapping the Go runtime's `protoreflect.Descriptor` implementations (which are more strict). But I think these are both manageable side effects. 🤞

**Pull request merged**
